const prefix =
    'https://firebasestorage.googleapis.com/v0/b/ssavis-d2333.appspot.com/o';

export const images = {
    logo: `${prefix}/logo.png?alt=media`,
    photo: `${prefix}/photo.png?alt=media`,
    cleaning: `${prefix}/cleaning.png?alt=media`,
    appliance: `${prefix}/appliance.png?alt=media`,
    invasion: `${prefix}/invasion.png?alt=media`,
    lostItem: `${prefix}/lostItem.png?alt=media`,
    cleaningG: `${prefix}/cleaning-gray.png?alt=media`,
    applianceG: `${prefix}/appliance-gray.png?alt=media`,
    invasionG: `${prefix}/invasion-gray.png?alt=media`,
    lostItemG: `${prefix}/lostItem-gray.png?alt=media`,
    all: `${prefix}/icons%2FALL.png?alt=media`,
    allG: `${prefix}/icons%2FALL_GRAY.png?alt=media`,
    selection: `${prefix}/icons%2FSELECTION.png?alt=media`,
    selectionG: `${prefix}/icons%2FSELECTION_GRAY.png?alt=media`,
    room: `${prefix}/icons%2Froom%2FBEDROOM.png?alt=media`,
    roomG: `${prefix}/icons%2Froom%2FBEDROOM%20GRAY.png?alt=media`,
    livingRoom: `${prefix}/icons%2Froom%2FLIVING%20ROOM.png?alt=media`,
    livingRoomG: `${prefix}/icons%2Froom%2FLIVING%20ROOM%20GRAY.png?alt=media`,
    kitchen: `${prefix}/icons%2Froom%2FKITCHEN.png?alt=media`,
    kitchenG: `${prefix}/icons%2Froom%2FKITCHEN%20GRAY.png?alt=media`,
    room2: `${prefix}/icons%2Froom%2FROOM2.png?alt=media`,
    room2G: `${prefix}/icons%2Froom%2FROOM2%20GRAY.png?alt=media`,
    aircon: `${prefix}/icons%2Fapp%2FAIRCON.png?alt=media`,
    airconG: `${prefix}/icons%2Fapp%2FAIRCON_GRAY.png?alt=media`,
    airpuri: `${prefix}/icons%2Fapp%2FAIRPURI.png?alt=media`,
    airpuriG: `${prefix}/icons%2Fapp%2FAIRPURI_GRAY.png?alt=media`,
    curtain: `${prefix}/icons%2Fapp%2FCURTAIN.png?alt=media`,
    curtainG: `${prefix}/icons%2Fapp%2FCURTAIN_GRAY.png?alt=media`,
    light: `${prefix}/icons%2Fapp%2FLIGHT.png?alt=media`,
    lightG: `${prefix}/icons%2Fapp%2FLIGHT_GRAY.png?alt=media`, 
    tv: `${prefix}/icons%2Fapp%2FTV.png?alt=media`,
    tvG: `${prefix}/icons%2Fapp%2FTV_GRAY.png?alt=media`,
};