export const lightTheme = {
    background: '#ffffff',
    text: '#000000',
    purple: '#9b59b6',
    blue: '#3498db',
    tabBackground: '#ffffff',
    imageBackground: '#A7F3D0',
    tabIcon:'grey',
    tabIconFocused:'#A7F3D0',
    label: 'grey',
    inputPlaceholder: 'grey',
    inputBorder: 'grey',
    errorText: 'red',
    buttonBackground: '#A7F3D0',
    buttonTitle:'white',
    buttonUnfilledTitle: '#A7F3D0',
    headerTintColor: '#A7F3D0',
    imageButtonBackground: '#92C5FC',
    imageButtonIcon: 'white',
    spinnerBackground: 'black',
    spinnerIndicator: 'white',
    Maintext:'#575757',
    mainButton: '#575757',
    mainButtonBack: 'white',
    font: 'NotoSansKR_700Bold',
};

export const darkTheme = {
    background: '#575757',
    text: '#ffffff',
    purple: '#9b59b6',
    blue: '#3498db',
    tabBackground: '#575757',
    imageBackground: '#ffffff',
    tabIcon:'grey',
    tabIconFocused:'#A7F3D0',
    label: 'grey',
    inputPlaceholder: 'grey',
    inputBorder: 'grey',
    errorText: 'red',
    buttonBackground: '#A7F3D0',
    buttonTitle:'white',
    buttonUnfilledTitle: '#A7F3D0',
    headerTintColor: '#A7F3D0',
    imageButtonBackground: '#92C5FC',
    imageButtonIcon: 'white',
    spinnerBackground: 'black',
    spinnerIndicator: 'white',
    Maintext:'white',
    mainButton: 'white',
    mainButtonBack: '#575757',
    font: 'NotoSansKR_700Bold',
};