//******************************************************************
// 
//  Generated by IDL to C++ Translator
//  
//  File name: ObjectXY_.h
//  Source: ssafy_msgs\msg\ObjectXY_.idl
//  Generated: timestamp removed to make the build reproducible
//  OpenSplice 6.9.190403OSS
//  
//******************************************************************
#ifndef _OBJECTXY__H_
#define _OBJECTXY__H_

#include "sacpp_mapping.h"
#include "ssafy_msgs/msg/rosidl_typesupport_opensplice_cpp__visibility_control.h"


namespace ssafy_msgs
{
   namespace msg
   {
      namespace dds_
      {
         struct ObjectXY_;

         struct ROSIDL_TYPESUPPORT_OPENSPLICE_CPP_PUBLIC_ssafy_msgs ObjectXY_
         {
               DDS::Float x_distance_;
               DDS::Float y_distance_;
         };

         typedef DDS_DCPSStruct_var < ObjectXY_> ObjectXY__var;
         typedef ObjectXY_&ObjectXY__out;
      }
   }
}




#endif
